import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Address from '#models/address'

export default class extends BaseSeeder {
  async run() {
    await Address.createMany([
      {
        customerId: 1,
        street: 'Rua A',
        number: '100',
        neighborhood: 'Bairro 1',
        city: 'Cidade 1',
        state: 'SP',
        zipCode: '01000-000',
      },
      {
        customerId: 2,
        street: 'Rua B',
        number: '101',
        neighborhood: 'Bairro 2',
        city: 'Cidade 2',
        state: 'RJ',
        zipCode: '02000-001',
      },
      {
        customerId: 3,
        street: 'Rua C',
        number: '102',
        neighborhood: 'Bairro 3',
        city: 'Cidade 3',
        state: 'MG',
        zipCode: '03000-002',
      },
      {
        customerId: 4,
        street: 'Rua D',
        number: '103',
        neighborhood: 'Bairro 4',
        city: 'Cidade 4',
        state: 'BA',
        zipCode: '04000-003',
      },
      {
        customerId: 5,
        street: 'Rua E',
        number: '104',
        neighborhood: 'Bairro 5',
        city: 'Cidade 5',
        state: 'RS',
        zipCode: '05000-004',
      },
      {
        customerId: 6,
        street: 'Rua F',
        number: '105',
        neighborhood: 'Bairro 6',
        city: 'Cidade 6',
        state: 'PR',
        zipCode: '06000-005',
      },
      {
        customerId: 7,
        street: 'Rua G',
        number: '106',
        neighborhood: 'Bairro 7',
        city: 'Cidade 7',
        state: 'SP',
        zipCode: '07000-006',
      },
      {
        customerId: 8,
        street: 'Rua H',
        number: '107',
        neighborhood: 'Bairro 8',
        city: 'Cidade 8',
        state: 'RJ',
        zipCode: '08000-007',
      },
      {
        customerId: 9,
        street: 'Rua I',
        number: '108',
        neighborhood: 'Bairro 9',
        city: 'Cidade 9',
        state: 'MG',
        zipCode: '09000-008',
      },
      {
        customerId: 10,
        street: 'Rua J',
        number: '109',
        neighborhood: 'Bairro 10',
        city: 'Cidade 10',
        state: 'BA',
        zipCode: '10000-009',
      },
      {
        customerId: 11,
        street: 'Rua K',
        number: '110',
        neighborhood: 'Bairro 11',
        city: 'Cidade 11',
        state: 'RS',
        zipCode: '11000-010',
      },
      {
        customerId: 12,
        street: 'Rua L',
        number: '111',
        neighborhood: 'Bairro 12',
        city: 'Cidade 12',
        state: 'PR',
        zipCode: '12000-011',
      },
      {
        customerId: 13,
        street: 'Rua M',
        number: '112',
        neighborhood: 'Bairro 13',
        city: 'Cidade 13',
        state: 'SP',
        zipCode: '13000-012',
      },
      {
        customerId: 14,
        street: 'Rua N',
        number: '113',
        neighborhood: 'Bairro 14',
        city: 'Cidade 14',
        state: 'RJ',
        zipCode: '14000-013',
      },
      {
        customerId: 15,
        street: 'Rua O',
        number: '114',
        neighborhood: 'Bairro 15',
        city: 'Cidade 15',
        state: 'MG',
        zipCode: '15000-014',
      },
      {
        customerId: 16,
        street: 'Rua P',
        number: '115',
        neighborhood: 'Bairro 16',
        city: 'Cidade 16',
        state: 'BA',
        zipCode: '16000-015',
      },
      {
        customerId: 17,
        street: 'Rua Q',
        number: '116',
        neighborhood: 'Bairro 17',
        city: 'Cidade 17',
        state: 'RS',
        zipCode: '17000-016',
      },
      {
        customerId: 18,
        street: 'Rua R',
        number: '117',
        neighborhood: 'Bairro 18',
        city: 'Cidade 18',
        state: 'PR',
        zipCode: '18000-017',
      },
      {
        customerId: 19,
        street: 'Rua S',
        number: '118',
        neighborhood: 'Bairro 19',
        city: 'Cidade 19',
        state: 'SP',
        zipCode: '19000-018',
      },
      {
        customerId: 20,
        street: 'Rua T',
        number: '119',
        neighborhood: 'Bairro 20',
        city: 'Cidade 20',
        state: 'RJ',
        zipCode: '20000-019',
      },
      {
        customerId: 21,
        street: 'Rua U',
        number: '120',
        neighborhood: 'Bairro 21',
        city: 'Cidade 21',
        state: 'MG',
        zipCode: '21000-020',
      },
      {
        customerId: 22,
        street: 'Rua V',
        number: '121',
        neighborhood: 'Bairro 22',
        city: 'Cidade 22',
        state: 'BA',
        zipCode: '22000-021',
      },
      {
        customerId: 23,
        street: 'Rua W',
        number: '122',
        neighborhood: 'Bairro 23',
        city: 'Cidade 23',
        state: 'RS',
        zipCode: '23000-022',
      },
      {
        customerId: 24,
        street: 'Rua X',
        number: '123',
        neighborhood: 'Bairro 24',
        city: 'Cidade 24',
        state: 'PR',
        zipCode: '24000-023',
      },
      {
        customerId: 25,
        street: 'Rua Y',
        number: '124',
        neighborhood: 'Bairro 25',
        city: 'Cidade 25',
        state: 'SP',
        zipCode: '25000-024',
      },
      {
        customerId: 26,
        street: 'Rua Z',
        number: '125',
        neighborhood: 'Bairro 26',
        city: 'Cidade 26',
        state: 'RJ',
        zipCode: '26000-025',
      },
      {
        customerId: 27,
        street: 'Rua AA',
        number: '126',
        neighborhood: 'Bairro 27',
        city: 'Cidade 27',
        state: 'MG',
        zipCode: '27000-026',
      },
      {
        customerId: 28,
        street: 'Rua BB',
        number: '127',
        neighborhood: 'Bairro 28',
        city: 'Cidade 28',
        state: 'BA',
        zipCode: '28000-027',
      },
      {
        customerId: 29,
        street: 'Rua CC',
        number: '128',
        neighborhood: 'Bairro 29',
        city: 'Cidade 29',
        state: 'RS',
        zipCode: '29000-028',
      },
      {
        customerId: 30,
        street: 'Rua DD',
        number: '129',
        neighborhood: 'Bairro 30',
        city: 'Cidade 30',
        state: 'PR',
        zipCode: '30000-029',
      },
      {
        customerId: 31,
        street: 'Rua EE',
        number: '130',
        neighborhood: 'Bairro 31',
        city: 'Cidade 31',
        state: 'SP',
        zipCode: '31000-030',
      },
      {
        customerId: 32,
        street: 'Rua FF',
        number: '131',
        neighborhood: 'Bairro 32',
        city: 'Cidade 32',
        state: 'RJ',
        zipCode: '32000-031',
      },
      {
        customerId: 33,
        street: 'Rua GG',
        number: '132',
        neighborhood: 'Bairro 33',
        city: 'Cidade 33',
        state: 'MG',
        zipCode: '33000-032',
      },
      {
        customerId: 34,
        street: 'Rua HH',
        number: '133',
        neighborhood: 'Bairro 34',
        city: 'Cidade 34',
        state: 'BA',
        zipCode: '34000-033',
      },
      {
        customerId: 35,
        street: 'Rua II',
        number: '134',
        neighborhood: 'Bairro 35',
        city: 'Cidade 35',
        state: 'RS',
        zipCode: '35000-034',
      },
      {
        customerId: 36,
        street: 'Rua JJ',
        number: '135',
        neighborhood: 'Bairro 36',
        city: 'Cidade 36',
        state: 'PR',
        zipCode: '36000-035',
      },
      {
        customerId: 37,
        street: 'Rua KK',
        number: '136',
        neighborhood: 'Bairro 37',
        city: 'Cidade 37',
        state: 'SP',
        zipCode: '37000-036',
      },
      {
        customerId: 38,
        street: 'Rua LL',
        number: '137',
        neighborhood: 'Bairro 38',
        city: 'Cidade 38',
        state: 'RJ',
        zipCode: '38000-037',
      },
      {
        customerId: 39,
        street: 'Rua MM',
        number: '138',
        neighborhood: 'Bairro 39',
        city: 'Cidade 39',
        state: 'MG',
        zipCode: '39000-038',
      },
      {
        customerId: 40,
        street: 'Rua NN',
        number: '139',
        neighborhood: 'Bairro 40',
        city: 'Cidade 40',
        state: 'BA',
        zipCode: '40000-039',
      },
      {
        customerId: 41,
        street: 'Rua OO',
        number: '140',
        neighborhood: 'Bairro 41',
        city: 'Cidade 41',
        state: 'RS',
        zipCode: '41000-040',
      },
      {
        customerId: 42,
        street: 'Rua PP',
        number: '141',
        neighborhood: 'Bairro 42',
        city: 'Cidade 42',
        state: 'PR',
        zipCode: '42000-041',
      },
      {
        customerId: 43,
        street: 'Rua QQ',
        number: '142',
        neighborhood: 'Bairro 43',
        city: 'Cidade 43',
        state: 'SP',
        zipCode: '43000-042',
      },
      {
        customerId: 44,
        street: 'Rua RR',
        number: '143',
        neighborhood: 'Bairro 44',
        city: 'Cidade 44',
        state: 'RJ',
        zipCode: '44000-043',
      },
      {
        customerId: 45,
        street: 'Rua SS',
        number: '144',
        neighborhood: 'Bairro 45',
        city: 'Cidade 45',
        state: 'MG',
        zipCode: '45000-044',
      },
      {
        customerId: 46,
        street: 'Rua TT',
        number: '145',
        neighborhood: 'Bairro 46',
        city: 'Cidade 46',
        state: 'BA',
        zipCode: '46000-045',
      },
      {
        customerId: 47,
        street: 'Rua UU',
        number: '146',
        neighborhood: 'Bairro 47',
        city: 'Cidade 47',
        state: 'RS',
        zipCode: '47000-046',
      },
      {
        customerId: 48,
        street: 'Rua VV',
        number: '147',
        neighborhood: 'Bairro 48',
        city: 'Cidade 48',
        state: 'PR',
        zipCode: '48000-047',
      },
      {
        customerId: 49,
        street: 'Rua WW',
        number: '148',
        neighborhood: 'Bairro 49',
        city: 'Cidade 49',
        state: 'SP',
        zipCode: '49000-048',
      },
      {
        customerId: 50,
        street: 'Rua XX',
        number: '149',
        neighborhood: 'Bairro 50',
        city: 'Cidade 50',
        state: 'RJ',
        zipCode: '50000-049',
      },
      {
        customerId: 51,
        street: 'Rua YY',
        number: '150',
        neighborhood: 'Bairro 51',
        city: 'Cidade 51',
        state: 'MG',
        zipCode: '51000-050',
      },
      {
        customerId: 52,
        street: 'Rua ZZ',
        number: '151',
        neighborhood: 'Bairro 52',
        city: 'Cidade 52',
        state: 'BA',
        zipCode: '52000-051',
      },
      {
        customerId: 53,
        street: 'Rua AAA',
        number: '152',
        neighborhood: 'Bairro 53',
        city: 'Cidade 53',
        state: 'RS',
        zipCode: '53000-052',
      },
      {
        customerId: 54,
        street: 'Rua BBB',
        number: '153',
        neighborhood: 'Bairro 54',
        city: 'Cidade 54',
        state: 'PR',
        zipCode: '54000-053',
      },
      {
        customerId: 55,
        street: 'Rua CCC',
        number: '154',
        neighborhood: 'Bairro 55',
        city: 'Cidade 55',
        state: 'SP',
        zipCode: '55000-054',
      },
      {
        customerId: 56,
        street: 'Rua DDD',
        number: '155',
        neighborhood: 'Bairro 56',
        city: 'Cidade 56',
        state: 'RJ',
        zipCode: '56000-055',
      },
      {
        customerId: 57,
        street: 'Rua EEE',
        number: '156',
        neighborhood: 'Bairro 57',
        city: 'Cidade 57',
        state: 'MG',
        zipCode: '57000-056',
      },
      {
        customerId: 58,
        street: 'Rua FFF',
        number: '157',
        neighborhood: 'Bairro 58',
        city: 'Cidade 58',
        state: 'BA',
        zipCode: '58000-057',
      },
      {
        customerId: 59,
        street: 'Rua GGG',
        number: '158',
        neighborhood: 'Bairro 59',
        city: 'Cidade 59',
        state: 'RS',
        zipCode: '59000-058',
      },
      {
        customerId: 60,
        street: 'Rua HHH',
        number: '159',
        neighborhood: 'Bairro 60',
        city: 'Cidade 60',
        state: 'PR',
        zipCode: '60000-059',
      },
      {
        customerId: 61,
        street: 'Rua III',
        number: '160',
        neighborhood: 'Bairro 61',
        city: 'Cidade 61',
        state: 'SP',
        zipCode: '61000-060',
      },
      {
        customerId: 62,
        street: 'Rua JJJ',
        number: '161',
        neighborhood: 'Bairro 62',
        city: 'Cidade 62',
        state: 'RJ',
        zipCode: '62000-061',
      },
      {
        customerId: 63,
        street: 'Rua KKK',
        number: '162',
        neighborhood: 'Bairro 63',
        city: 'Cidade 63',
        state: 'MG',
        zipCode: '63000-062',
      },
      {
        customerId: 64,
        street: 'Rua LLL',
        number: '163',
        neighborhood: 'Bairro 64',
        city: 'Cidade 64',
        state: 'BA',
        zipCode: '64000-063',
      },
      {
        customerId: 65,
        street: 'Rua MMM',
        number: '164',
        neighborhood: 'Bairro 65',
        city: 'Cidade 65',
        state: 'RS',
        zipCode: '65000-064',
      },
    ])
  }
}
