import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Address from '#models/address'

export default class extends BaseSeeder {
  async run() {
    await Address.createMany([
      {
        customerId: 1,
        street: 'Avenida Paulista',
        number: '100',
        neighborhood: 'Bela Vista',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01000-000',
        country: 'Brasil',
      },
      {
        customerId: 2,
        street: 'Rua das Laranjeiras',
        number: '101',
        neighborhood: 'Laranjeiras',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '02000-001',
        country: 'Brasil',
      },
      {
        customerId: 3,
        street: 'Avenida Afonso Pena',
        number: '102',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '03000-002',
        country: 'Brasil',
      },
      {
        customerId: 4,
        street: 'Avenida Sete de Setembro',
        number: '103',
        neighborhood: 'Centro',
        city: 'Salvador',
        state: 'BA',
        zipCode: '04000-003',
        country: 'Brasil',
      },
      {
        customerId: 5,
        street: 'Rua dos Andradas',
        number: '104',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '05000-004',
        country: 'Brasil',
      },
      {
        customerId: 6,
        street: 'Rua XV de Novembro',
        number: '105',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '06000-005',
        country: 'Brasil',
      },
      {
        customerId: 7,
        street: 'Rua da Consolação',
        number: '106',
        neighborhood: 'Consolação',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '07000-006',
        country: 'Brasil',
      },
      {
        customerId: 8,
        street: 'Rua Voluntários da Pátria',
        number: '107',
        neighborhood: 'Botafogo',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '08000-007',
        country: 'Brasil',
      },
      {
        customerId: 9,
        street: 'Rua Guaicuí',
        number: '108',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '09000-008',
        country: 'Brasil',
      },
      {
        customerId: 10,
        street: 'Rua da Bahia',
        number: '109',
        neighborhood: 'Rio Vermelho',
        city: 'Salvador',
        state: 'BA',
        zipCode: '10000-009',
        country: 'Brasil',
      },
      {
        customerId: 11,
        street: 'Rua dos Três Vendas',
        number: '110',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '11000-010',
        country: 'Brasil',
      },
      {
        customerId: 12,
        street: 'Avenida João Gualberto',
        number: '111',
        neighborhood: 'Cristo Rei',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '12000-011',
        country: 'Brasil',
      },
      {
        customerId: 13,
        street: 'Rua dos Três Irmãos',
        number: '112',
        neighborhood: 'Vila Progredior',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '13000-012',
        country: 'Brasil',
      },
      {
        customerId: 14,
        street: 'Rua General Canabarro',
        number: '113',
        neighborhood: 'Ipanema',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '14000-013',
        country: 'Brasil',
      },
      {
        customerId: 15,
        street: 'Rua São Paulo',
        number: '114',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '15000-014',
        country: 'Brasil',
      },
      {
        customerId: 16,
        street: 'Avenida Paralela',
        number: '115',
        neighborhood: 'Pituba',
        city: 'Salvador',
        state: 'BA',
        zipCode: '16000-015',
        country: 'Brasil',
      },
      {
        customerId: 17,
        street: 'Rua Bento Gonçalves',
        number: '116',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '17000-016',
        country: 'Brasil',
      },
      {
        customerId: 18,
        street: 'Rua do Porto',
        number: '117',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '18000-017',
        country: 'Brasil',
      },
      {
        customerId: 19,
        street: 'Avenida São João',
        number: '118',
        neighborhood: 'Centro',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '19000-018',
        country: 'Brasil',
      },
      {
        customerId: 20,
        street: 'Rua da Tijuca',
        number: '119',
        neighborhood: 'Tijuca',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '20000-019',
        country: 'Brasil',
      },
      {
        customerId: 21,
        street: 'Rua dos Timbiras',
        number: '120',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '21000-020',
        country: 'Brasil',
      },
      {
        customerId: 22,
        street: 'Avenida 7 de Setembro',
        number: '121',
        neighborhood: 'Cidade Alta',
        city: 'Salvador',
        state: 'BA',
        zipCode: '22000-021',
        country: 'Brasil',
      },
      {
        customerId: 23,
        street: 'Rua João Pessoa',
        number: '122',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '23000-022',
        country: 'Brasil',
      },
      {
        customerId: 24,
        street: 'Rua do Catete',
        number: '123',
        neighborhood: 'Catete',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '24000-023',
        country: 'Brasil',
      },
      {
        customerId: 25,
        street: 'Rua dos Três Corações',
        number: '124',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '25000-024',
        country: 'Brasil',
      },
      {
        customerId: 26,
        street: 'Rua Visconde de Pirajá',
        number: '125',
        neighborhood: 'Ipanema',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '26000-025',
        country: 'Brasil',
      },
      {
        customerId: 27,
        street: 'Rua dos Três Irmãos',
        number: '126',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '27000-026',
        country: 'Brasil',
      },
      {
        customerId: 28,
        street: 'Rua da Independência',
        number: '127',
        neighborhood: 'Independência',
        city: 'Salvador',
        state: 'BA',
        zipCode: '28000-027',
        country: 'Brasil',
      },
      {
        customerId: 29,
        street: 'Rua Almirante Barroso',
        number: '128',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '29000-028',
        country: 'Brasil',
      },
      {
        customerId: 30,
        street: 'Avenida Beira-Mar',
        number: '129',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '30000-029',
        country: 'Brasil',
      },
      {
        customerId: 31,
        street: 'Rua da Figueira',
        number: '130',
        neighborhood: 'Vila Progredior',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '31000-030',
        country: 'Brasil',
      },
      {
        customerId: 32,
        street: 'Rua do Passeio',
        number: '131',
        neighborhood: 'Centro',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '32000-031',
        country: 'Brasil',
      },
      {
        customerId: 33,
        street: 'Avenida Cristiano Machado',
        number: '132',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '33000-032',
        country: 'Brasil',
      },
      {
        customerId: 34,
        street: 'Rua Alagoas',
        number: '133',
        neighborhood: 'Vila Progredior',
        city: 'Salvador',
        state: 'BA',
        zipCode: '34000-033',
        country: 'Brasil',
      },
      {
        customerId: 35,
        street: 'Rua Marques de São Vicente',
        number: '134',
        neighborhood: 'Santa Teresa',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '35000-034',
        country: 'Brasil',
      },
      {
        customerId: 36,
        street: 'Rua Dona Maria',
        number: '135',
        neighborhood: 'Vila Maria',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '36000-035',
        country: 'Brasil',
      },
      {
        customerId: 37,
        street: 'Rua dos Carijós',
        number: '136',
        neighborhood: 'Vila Progresso',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '37000-036',
        country: 'Brasil',
      },
      {
        customerId: 38,
        street: 'Rua General Osório',
        number: '137',
        neighborhood: 'Tijuca',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '38000-037',
        country: 'Brasil',
      },
      {
        customerId: 39,
        street: 'Rua das Palmeiras',
        number: '138',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '39000-038',
        country: 'Brasil',
      },
      {
        customerId: 40,
        street: 'Avenida Vinte de Julho',
        number: '139',
        neighborhood: 'Rio Vermelho',
        city: 'Salvador',
        state: 'BA',
        zipCode: '40000-039',
        country: 'Brasil',
      },
      {
        customerId: 41,
        street: 'Rua Vitória Régia',
        number: '140',
        neighborhood: 'Vila Marçola',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '41000-040',
        country: 'Brasil',
      },
      {
        customerId: 42,
        street: 'Rua Benjamin Constant',
        number: '141',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '42000-041',
        country: 'Brasil',
      },
      {
        customerId: 43,
        street: 'Avenida João Pessoa',
        number: '142',
        neighborhood: 'Centro',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '43000-042',
        country: 'Brasil',
      },
      {
        customerId: 44,
        street: 'Rua Siqueira Campos',
        number: '143',
        neighborhood: 'Tijuca',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '44000-043',
        country: 'Brasil',
      },
      {
        customerId: 45,
        street: 'Rua dos Três Corações',
        number: '144',
        neighborhood: 'Vila Sônia',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '45000-044',
        country: 'Brasil',
      },
      {
        customerId: 46,
        street: 'Rua Costa e Silva',
        number: '145',
        neighborhood: 'Pituba',
        city: 'Salvador',
        state: 'BA',
        zipCode: '46000-045',
        country: 'Brasil',
      },
      {
        customerId: 47,
        street: 'Avenida Getúlio Vargas',
        number: '146',
        neighborhood: 'Centro',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '47000-046',
        country: 'Brasil',
      },
      {
        customerId: 48,
        street: 'Rua Jardim Botânico',
        number: '147',
        neighborhood: 'Jardim Botânico',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '48000-047',
        country: 'Brasil',
      },
      {
        customerId: 49,
        street: 'Rua Afonso Pena',
        number: '148',
        neighborhood: 'Afonso Pena',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '49000-048',
        country: 'Brasil',
      },
      {
        customerId: 50,
        street: 'Avenida João Paulo',
        number: '149',
        neighborhood: 'Centro',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '50000-049',
        country: 'Brasil',
      },
      {
        customerId: 51,
        street: 'Rua São Sebastião',
        number: '150',
        neighborhood: 'Vila Nova',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '51000-050',
        country: 'Brasil',
      },
      {
        customerId: 52,
        street: 'Rua Rio Branco',
        number: '151',
        neighborhood: 'Centro',
        city: 'Salvador',
        state: 'BA',
        zipCode: '52000-051',
        country: 'Brasil',
      },
      {
        customerId: 53,
        street: 'Rua Comendador Abílio Soares',
        number: '152',
        neighborhood: 'Bairro Brasil',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '53000-052',
        country: 'Brasil',
      },
      {
        customerId: 54,
        street: 'Rua das Acácias',
        number: '153',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '54000-053',
        country: 'Brasil',
      },
      {
        customerId: 55,
        street: 'Rua Alagoas',
        number: '154',
        neighborhood: 'Vila Progredior',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '55000-054',
        country: 'Brasil',
      },
      {
        customerId: 56,
        street: 'Rua Nossa Senhora da Glória',
        number: '155',
        neighborhood: 'Glória',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '56000-055',
        country: 'Brasil',
      },
      {
        customerId: 57,
        street: 'Rua do Salitre',
        number: '156',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '57000-056',
        country: 'Brasil',
      },
      {
        customerId: 58,
        street: 'Rua da Paz',
        number: '157',
        neighborhood: 'Vila Cruzeiro',
        city: 'Salvador',
        state: 'BA',
        zipCode: '58000-057',
        country: 'Brasil',
      },
      {
        customerId: 59,
        street: 'Rua dos Três Irmãos',
        number: '158',
        neighborhood: 'Pituba',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '59000-058',
        country: 'Brasil',
      },
      {
        customerId: 60,
        street: 'Rua Getúlio Vargas',
        number: '159',
        neighborhood: 'Centro',
        city: 'Curitiba',
        state: 'PR',
        zipCode: '60000-059',
        country: 'Brasil',
      },
      {
        customerId: 61,
        street: 'Rua Francisco Matarazzo',
        number: '160',
        neighborhood: 'Vila Matarazzo',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '61000-060',
        country: 'Brasil',
      },
      {
        customerId: 62,
        street: 'Rua Leopoldo',
        number: '161',
        neighborhood: 'Jardim Leopoldina',
        city: 'Rio de Janeiro',
        state: 'RJ',
        zipCode: '62000-061',
        country: 'Brasil',
      },
      {
        customerId: 63,
        street: 'Rua São José',
        number: '162',
        neighborhood: 'Vila Progresso',
        city: 'Belo Horizonte',
        state: 'MG',
        zipCode: '63000-062',
        country: 'Brasil',
      },
      {
        customerId: 64,
        street: 'Avenida Jorge Amado',
        number: '163',
        neighborhood: 'Vila Jardim',
        city: 'Salvador',
        state: 'BA',
        zipCode: '64000-063',
        country: 'Brasil',
      },
      {
        customerId: 65,
        street: 'Rua Amazonas',
        number: '164',
        neighborhood: 'Vila Nova',
        city: 'Porto Alegre',
        state: 'RS',
        zipCode: '65000-064',
        country: 'Brasil',
      },
    ])
  }
}
