services:

  backend:
    build:
      context: .
    container_name: betalent_backend
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=adonis_db

  database:
    image: mysql:latest
    container_name: betalent_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis_db
    ports:
      - "3306:3306"