services:

  backend:
    build:
      context: .
    container_name: betalent_backend
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=adonis_db

  database:
    image: mysql:latest
    container_name: betalent_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"